version: '3.8'
services:
  gitlab:
    container_name: gitlab
    image: 'gitlab/gitlab-ee:latest'
    restart: always
    hostname: 'gitlab.rwwilden.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.rwwilden.com:8929'
    ports:
      - '8929:8929'
      - '2289:22'
    volumes:
      - "./gitlab/config:/etc/gitlab"
      - "./gitlab/logs:/var/log/gitlab"
      - "./gitlab/data:/var/opt/gitlab"
    shm_size: '256m'
  
  gitlab-runner:
    container_name: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./runner/builds:/builds"
      - "./runner/cache:/cache"
      - "./runner/config:/etc/gitlab-runner"
      - "./runner/scripts:/scripts"